version: "3.1"
services:

  mailhog:
    image: mailhog/mailhog:latest
    container_name: aviv-inventorybackend-mailhog
    ports:
      - "4001:8025"

  redis:
    image: redis:alpine
    container_name: aviv-inventorybackend-redis

  mysql:
    image: mysql:8.0
    container_name: aviv-inventorybackend-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswordhere
      - MYSQL_DATABASE=inventorydb
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: aviv-inventorybackend-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./backend/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:80"

  php-fpm:
    build: ./backend/phpdocker/php-fpm
    container_name: aviv-inventorybackend-php-fpm
    working_dir: /application
    volumes:
      - ./backend:/application
      - ./backend/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini


  node1:
    build: ./front/npvuedocker/node
    container_name: aviv-inventoryfront-node
    working_dir: /application
    volumes:
      - ./front:/application
    ports:
      - "8080:8081"

  # docker exec -it aviv-inventorybackend-php-fpm bash
  #find /application/ -type f -exec chmod 644 {} \;
  #find /application -type d -exec chmod 755 {} \;
  #chown -R 1000:1000 /application/
  #chmod -R 777 /application/storage
  #chmod -R 777 /application/bootstrap/cache/
  #chmod -R 777 /application/public/

